import { Service, Config } from "@cmmv/core";

@Service()
export class DeepSeekService {
    async generateContent(prompt: string) : Promise<string> {
        const deepseekApiKey = Config.get("blog.deepseekApiKey");
        const timeout = Config.get("blog.aiTimeout", 90000); // 90 segundos por padrão

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), timeout);

        try {
            const response = await fetch('https://api.deepseek.com/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${deepseekApiKey || ''}`
                },
                body: JSON.stringify({
                    model: "deepseek-chat",
                    messages: [
                        {
                            role: "user",
                            content: prompt
                        }
                    ],
                    temperature: 0.1,
                    top_p: 0.9,
                    max_tokens: 8192
                }),
                signal: controller.signal
            });

            clearTimeout(timeoutId);

            if (!response.ok)
                throw new Error(`Failed to generate AI content: ${await response.text()}`);

            const deepseekResponse = await response.json();
            const generatedText = deepseekResponse.choices?.[0]?.message?.content;

            if (!generatedText)
                throw new Error('No content generated by DeepSeek');

            return generatedText;
        } catch (error) {
            clearTimeout(timeoutId);
            
            if (error.name === 'AbortError') {
                throw new Error(`DeepSeek AI timeout after ${timeout}ms`);
            }
            
            throw error;
        }
    }
}
